moviesApp/urls.py
from django.conf.urls import url
from . import views

app_name='movies'

urlpatterns = [
	#movies
	url(r'^$', views.homepage, name='homepage'),
	
    #/movies/genres/
	url(r'^genres/', views.genres, name='genres'),
	
	#/movies/id/
	url(r'^(?P<genre_id>[0-9]+)/$', views.genreMovies, name='genres'),
	
	#/movies/favorite/
	url(r'^(?P<genre_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
	
	#/movies/movies/
	url(r'^movies/', views.movies, name='movies'),
	
	#/movies/movie/<movie_id>
	url(r'^movie/(?P<movie_id>[0-9]+)/$', views.get_movie, name='get_movie'),
	
	#/movies/login/
	url(r'^login/', views.login_user, name='login_user'),
	
	#/movies/logout/
	url(r'^logout/', views.logout_user, name='logout_user'),
	
	#/movies/register/
	url(r'^register/', views.register, name='register'),
	
	#movies/create_genre
	url(r'^create_genre/', views.create_genre, name='create_genre'),
	
	#movies/<genre_id>/add_movie
	url(r'^(?P<genre_id>[0-9]+)/add_movie/$', views.add_movie, name='add_movie'),
	
	#movies/search
	url(r'^search/', views.search, name='search'),
	
]

moviesApp/models.py
from django.db import models

class Genre(models.Model):
    genreName=models.CharField(max_length=250)
    def __str__(self):
        return self.genreName
	
class Movie(models.Model):
    genre=models.ForeignKey(Genre, on_delete=models.CASCADE)
    title=models.CharField(max_length=250)
    logo=models.CharField(max_length=1000)
    rating=models.CharField(max_length=250)
    description=models.CharField(max_length=500)
    releasedate=models.DateField(max_length=250)
    is_favorite= models.BooleanField(default=False)
	
    def __str__(self):
        return self.title

moviesApp/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Movie, Genre

class GenreForm(forms.ModelForm):
    #clasa Meta contine informatii despre clasa
    class Meta:
        model = Genre
        fields = ['genreName']


class MovieForm(forms.ModelForm):

    class Meta:
        model = Movie
        fields = ['title', 'rating', 'releasedate', 'description']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

moviesApp/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Genre, Movie
from .forms import GenreForm, MovieForm, UserForm
from django.http import Http404, HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout

def homepage(request):
    all_genres=Genre.objects.all()
    all_movies=Movie.objects.all()
    return render(request, 'movies/homepage.html', {'all_genres': all_genres, 'all_movies': all_movies})

def genres(request):
    all_genres=Genre.objects.all()
    return render(request, 'movies/list_all.html', {'all_genres': all_genres})

def genreMovies(request, genre_id):
    genre=get_object_or_404(Genre, pk= genre_id)
    return render(request, 'movies/genre_movies.html', {'genre': genre})
    
def favorite(request, genre_id):
    genre=get_object_or_404(Genre, pk= genre_id)
    try: 
	    selected_movie = genre.movie_set.get(pk=request.POST['movie'])
    except (KeyError, Movie.DoesNotExist):
	    return render(request,'movies/genre_movies.html', {
		'genre': genre,
		'error_message': "You did not select a valid movie",
		})
    else: 
	    selected_movie.is_favorite = True
	    selected_movie.save()
	    return render(request, 'movies/genre_movies.html', {'genre': genre})

def movies(request):
    all_movies=Movie.objects.all()
    return render(request, 'movies/movies.html', {'all_movies': all_movies,})
	
def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('movies:homepage')
            else:
                return render(request, 'movies/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'movies/login.html', {'error_message': 'Invalid login'})
    return render(request, 'movies/login.html')

def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'movies/login.html', context)
	
def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('movies:homepage')
    context = {
        'form': form,
    }
    return render(request, 'movies/register.html', context)

def create_genre(request):
    #if not request.user.is_authenticated():
    #    return render(request, 'movies/login.html')
    #else:
        form = GenreForm(request.POST or None, request.FILES or None)
        genres=Genre.objects.all()
        if form.is_valid():
            genre = form.save(commit=False)
            genreName=form.cleaned_data['genreName']
            for g in genres:
                if g.genreName ==  form.cleaned_data.get("genreName"):
                    context = {
                        'form': form,
						'error_message': 'The genre is already added',
					}
                    return render(request, 'movies/create_genre.html', context)
            genre.save()
            if genre is not None:
                return redirect('movies:genres')
        context = {
            'form': form,
        }
        return render(request, 'movies/create_genre.html', context)

def add_movie(request, genre_id):
    form = MovieForm(request.POST or None)
    genre = get_object_or_404(Genre, pk=genre_id)
    if form.is_valid():
        genre_movies = genre.movie_set.all()
        movie = form.save(commit=False)
        movie.genre = genre
        movie.title = form.cleaned_data['title']
        for s in genre_movies:
            if s.title == form.cleaned_data.get("title"):
                context = {
                    'genre': genre,
                    'form': form,
                    'error_message': 'You already added that movie',
                }
                return render(request, 'movies/create_movie.html', context)
       
        movie.save()
        if movie is not None:
                return redirect('movies:movies')
    context = {
        'genre': genre,
        'form': form,
    }
    return render(request, 'movies/create_movie.html', context)	
	
def search(request):
    if request.method=="POST":
	    search_text=request.POST['search']
    else:
        search_text=''
    movies=Movie.objects.filter(title__contains=search_text)
    return render(request, 'layout/header.html', {'movies':movies})
	
def get_movie(request, movie_id):
    movie=get_object_or_404(Movie, pk= movie_id)
    return render(request, 'movies/get_movies.html', {'movie': movie})

moviesApp/templates/layout/base_layout.html
{% load static %}
<html>
    <head>
        <title>Movies</title>
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	   <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    </head>
    <body>
		{% include "layout/header.html" %}
        <div class="content container">
		 {% block content %}
         {% endblock %}
        </div>
    </body>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</html>

moviesApp/templates/layout/header.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/movies/">Homepage</a>
  <a class="navbar-brand" href="/movies/movies">Movies</a>
  <a class="navbar-brand" href="/movies/genres">Genres</a>
  <a class="navbar-brand" href="/movies/robot">Robot</a>
  <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name='search'>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
  </form>
  <a class="navbar-brand" href="/movies/login">Log In</a>
  <a class="navbar-brand" href="/movies/register">Register</a>
  <a class="navbar-brand" href="/movies/create_genre">Create Genre</a>
</nav>

moviesApp/templates/movies/create_genre.html
{% extends 'layout/base_layout.html' %}
{% block content %}

<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Genre</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'movies/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>

{% endblock %}

moviesApp/templates/movies/create_movie.html
{% extends 'layout/base_layout.html' %}
{% block content %}

<div class="container-fluid">

    <div class="row">

        <!-- Left Genre Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h1>{{ genre.genreName }} </h1>
                </div>
            </div>
        </div>

        <!-- Right Movie Info -->
        <div class="col-sm-8 col-md-9">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Movie</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="genre" value="{{ genre }}">
                        {% include 'movies/form_template.html' %}
						
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>


</div>

{% endblock %}

moviesApp/templates/movies/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

moviesApp/templates/movies/genre_movies.html
{% extends 'layout/base_layout.html' %}
{% block content %}
<h4>Movies for {{genre.genreName}} genre:</h4>

{% if error_message%}
<div class="alert alert-danger" role="alert">
	{{error_message}}
</div>

{% endif %}

<form action="/movies/{{ genre.id }}/favorite/" method="post">
	{% csrf_token %}
	<div class="row">
		{% for movie in genre.movie_set.all %}
			<div style="margin-top: 5px;" class="col col-xs-12 col-sm-12 col-md-12 col-lg-4">
				<div class="card">
				  <div class="card-body">
					<h5 class="card-title">
					{% if movie.is_favorite %}
						<img src= "http://i.imgur.com/b9b13Rd.png" />
					{% endif %} {{movie.title}}</h5>
					<h6 class="card-subtitle mb-2 text-muted">{{movie.releasedate}} ({{movie.rating}})</h6> 
					<p class="card-text">{{movie.description}}</p> 
					<input type="radio" id="movie{{ forloop.counter }}" name="movie" value="{{ movie.id }}"/>
					<label for="movie{{ forloop.counter }}" class="card-link">Favorite</label>
				  </div>
				</div>
			</div>
		{% endfor %}
	</div>
	<div class="row">
		<div class="col">
			<input type="submit" class="btn btn-primary" value="Favorite">
		</div>
		<div class="col">
			<a href="/movies/{{ genre.id }}/add_movie/">
				<input type="button" class="btn btn-primary" value="Add Movie">
		</div>
	</div>
	
</form>

	

{% endblock %}

moviesApp/templates/movies/get_movies.html
{% extends 'layout/base_layout.html' %}
{% block content %}

{% if error_message%}
<div class="alert alert-danger" role="alert">
	{{error_message}}
</div>
{% endif %}

<form action="/movies/movies/{{ movie.id }}/" method="post">
	{% csrf_token %}
	<div class="row">
			<div style="margin-top: 5px;" class="col col-xs-12 col-sm-12 col-md-12 col-lg-4">
				<div class="card">
				  <div class="card-body">
				    <h5 class="card-title">{{movie.title}}</h5>
					<h6 class="card-subtitle mb-2 text-muted">{{movie.releasedate}} ({{movie.rating}})</h6> 
					<p class="card-text">{{movie.description}}</p> 
				  </div>
				</div>
			</div>
	</div>
</form>
{% endblock %}

moviesApp/templates/movies/homepage.html
{% extends 'layout/base_layout.html' %}
{% block content %}
<h4>Welcome to our website!</h4><br>
{% if all_genres %}
    <h5>All existing genres are listed below:</h5>
	<div>
        {%for genre in all_genres %}
			<div class="card" style="width: 18rem;">
			  <div class="card-body">
				<h5 class="card-title">{{ genre.genreName }}</h5>
				<a href="/movies/{{ genre.id }}/" class="card-link">See the Movies</a>
			  </div>
			</div>
	    {% endfor %}
	</div>
{% else %}
    <div class="alert alert-primary" role="alert">Currently there's no genre in the database</div>
{% endif %}
<br>
<br>
{% if all_movies %}
    <h5>All existing movies are listed below:</h5>
	<div>
        {%for movie in all_movies %}
			<div style="margin-top: 5px;" class="col col-xs-12 col-sm-12 col-md-12 col-lg-4">
				<div class="card">
				  <div class="card-body">
					<h5 class="card-title">{{movie.title}}</h5>
					<h6 class="card-subtitle mb-2 text-muted">{{movie.releasedate}} ({{movie.rating}})</h6> 
					<p class="card-text">{{movie.description}}</p> 
				  </div>
				</div>
			</div>
	    {% endfor %}
	</div>
{% else %}
    <div class="alert alert-primary" role="alert">Currently there's no genre in the database</div>
{% endif %}
{% endblock %}	

moviesApp/templates/movies/list_all.html
{% extends 'layout/base_layout.html' %}
{% block content %}

{% if all_genres %}
    <h5>All existing genres are listed below:</h5>
	<div>
        {%for genre in all_genres %}
			<div class="card" style="width: 18rem;">
			  <div class="card-body">
				<h5 class="card-title">{{ genre.genreName }}</h5>
				<a href="/movies/{{ genre.id }}/" class="card-link">See the Movies</a>
			  </div>
			</div>
	    {% endfor %}
	</div>
{% else %}
    <div class="alert alert-primary" role="alert">Currently there's no genre in the database</div>
{% endif %}
{% endblock %}	
	

moviesApp/templates/movies/logged_user.html
{% load static %}
<html>
    <head>
        <title>Movies</title>
       <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	   <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    </head>
    <body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand" href="/movies/">Homepage</a>
			<a class="navbar-brand" href="/movies/movies">Movies</a>
			<a class="navbar-brand" href="/movies/genres">Genres</a>
			<a class="navbar-brand" href="/movies/robot">Robot</a>
			<form class="form-inline my-2 my-lg-0">
			    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
				<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form>
			<a class="navbar-brand" href="/movies/logout">Log Out</a>
			<a class="navbar-brand" href="/movies/register">Register</a>
</nav>
        <div class="content container">
		 {% block content %}
         {% endblock %}
        </div>
    </body>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</html>
{% block content %}
{% if all_genres %}
    <h5>All existing genres are listed below:</h5>
	<div>
        {%for genre in all_genres %}
			<div class="card" style="width: 18rem;">
			  <div class="card-body">
				<h5 class="card-title">{{ genre.genreName }}</h5>
				<a href="/movies/{{ genre.id }}/" class="card-link">See the Movies</a>
			  </div>
			</div>
	    {% endfor %}
	</div>
{% else %}
    <div class="alert alert-primary" role="alert">Currently there's no genre in the database</div>
{% endif %}
<br>
<br>
{% if all_movies %}
    <h5>All existing movies are listed below:</h5>
	<div>
        {%for movie in all_movies %}
			<div style="margin-top: 5px;" class="col col-xs-12 col-sm-12 col-md-12 col-lg-4">
				<div class="card">
				  <div class="card-body">
					<h5 class="card-title">{{movie.title}}</h5>
					<h6 class="card-subtitle mb-2 text-muted">{{movie.releasedate}} ({{movie.rating}})</h6> 
					<p class="card-text">{{movie.description}}</p> 
				  </div>
				</div>
			</div>
	    {% endfor %}
	</div>
{% else %}
    <div class="alert alert-primary" role="alert">Currently there's no genre in the database</div>
{% endif %}
{% endblock %}

moviesApp/templates/movies/login.html
{% extends 'layout/base_layout.html'%}
{% block content %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'movies:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'movies:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

moviesApp/templates/movies/movies.html
{% extends 'layout/base_layout.html' %}
{% block content %}
{% if all_movies %}
    <h5>All existing movies are listed below:</h5>
	<div>
        {%for movie in all_movies %}
			<div style="margin-top: 5px;" class="col col-xs-12 col-sm-12 col-md-12 col-lg-4">
				<div class="card">
				  <div class="card-body">
					<h5 class="card-title">
					{% if movie.is_favorite %}
						<img src= "http://i.imgur.com/b9b13Rd.png" />
					{% endif %} {{movie.title}}</h5>
					<h6 class="card-subtitle mb-2 text-muted">{{movie.releasedate}} ({{movie.rating}})</h6> 
					<p class="card-text">{{movie.description}}</p> 
					<input type="radio" id="movie{{ forloop.counter }}" name="movie" value="{{ movie.id }}"/>
					<label for="movie{{ forloop.counter }}" class="card-link">Favorite</label>
				  </div>
				</div>
			</div>
	    {% endfor %}
	</div>
{% else %}
    <div class="alert alert-primary" role="alert">Currently there's no genre in the database</div>
{% endif %}
{% endblock %}	

moviesApp/templates/movies/register.html
{% extends 'layout/base_layout.html'%}
{% block content %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'movies/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'movies:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}

moviesApp/templates/movies/search.html
{% if movies.count > 0%}

{% for movie in movies %}
	<li><a href="/movies/movie/{{ movie.id }}/>" {{ movie.title }}</a></li>
{% endfor %}

{% else %}

<li>None to show!</li>

{% endif %}